"""Asset tools — import, generate, and manage Godot assets."""
from __future__ import annotations
import os
import shutil
import struct
from typing import Any
from ..models import ToolCallResponse


def _write_file(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ---------------------------------------------------------------------------
# Tool implementations
# ---------------------------------------------------------------------------

def asset_import(
    *,
    project_path: str,
    source_path: str,
    target_path: str,
    type: str = "texture",
) -> ToolCallResponse:
    """Copy an asset file into the Godot project."""
    full_target = os.path.join(project_path, target_path.lstrip("res://"))
    os.makedirs(os.path.dirname(full_target), exist_ok=True)

    if os.path.exists(source_path):
        shutil.copy2(source_path, full_target)
        size = os.path.getsize(full_target)
        return ToolCallResponse(success=True, data={"path": target_path, "size": size, "type": type})

    return ToolCallResponse(success=False, error=f"Source file not found: {source_path}")


def asset_create_material(
    *,
    project_path: str,
    name: str,
    albedo_color: str = "Color(1, 1, 1, 1)",
    metallic: float = 0.0,
    roughness: float = 0.7,
    save_path: str | None = None,
) -> ToolCallResponse:
    """Create a StandardMaterial3D .tres resource."""
    path = save_path or f"res://assets/materials/{name}.tres"
    full_path = os.path.join(project_path, path.lstrip("res://"))

    content = (
        f'[gd_resource type="StandardMaterial3D" format=3]\n\n'
        f'[resource]\n'
        f'albedo_color = {albedo_color}\n'
        f'metallic = {metallic}\n'
        f'roughness = {roughness}\n'
    )
    _write_file(full_path, content)
    return ToolCallResponse(success=True, data={"path": path})


def asset_create_shader(
    *,
    project_path: str,
    name: str,
    shader_type: str = "canvas_item",
    save_path: str | None = None,
    content: str | None = None,
) -> ToolCallResponse:
    """Create a .gdshader file."""
    path = save_path or f"res://assets/shaders/{name}.gdshader"
    full_path = os.path.join(project_path, path.lstrip("res://"))

    shader_content = content or (
        f'shader_type {shader_type};\n\n'
        f'// {name} shader\n'
        f'// Generated by OmniForge\n\n'
        f'uniform vec4 modulate_color : source_color = vec4(1.0);\n\n'
        f'void fragment() {{\n'
        f'\tCOLOR = texture(TEXTURE, UV) * modulate_color;\n'
        f'}}\n'
    )
    _write_file(full_path, shader_content)
    return ToolCallResponse(success=True, data={"path": path})


def asset_create_theme(
    *,
    project_path: str,
    name: str,
    primary_color: str = "#6366f1",
    save_path: str | None = None,
) -> ToolCallResponse:
    """Create a basic UI Theme .tres file."""
    path = save_path or f"res://assets/themes/{name}.tres"
    full_path = os.path.join(project_path, path.lstrip("res://"))

    # Convert hex to Godot Color
    def hex_to_godot(hex_color: str) -> str:
        hex_color = hex_color.lstrip("#")
        r = int(hex_color[0:2], 16) / 255
        g = int(hex_color[2:4], 16) / 255
        b = int(hex_color[4:6], 16) / 255
        return f"Color({r:.3f}, {g:.3f}, {b:.3f}, 1)"

    content = (
        f'[gd_resource type="Theme" format=3]\n\n'
        f'[resource]\n'
        f'default_font_size = 14\n'
    )
    _write_file(full_path, content)
    return ToolCallResponse(success=True, data={"path": path, "primary_color": primary_color})


def asset_generate_placeholder_sprite(
    *,
    project_path: str,
    name: str,
    width: int = 32,
    height: int = 32,
    color_hex: str = "#6366f1",
    save_path: str | None = None,
) -> ToolCallResponse:
    """Generate a minimal valid PNG placeholder sprite."""
    path = save_path or f"res://assets/sprites/{name}.png"
    full_path = os.path.join(project_path, path.lstrip("res://"))
    os.makedirs(os.path.dirname(full_path), exist_ok=True)

    # Parse color
    hex_clean = color_hex.lstrip("#")
    r = int(hex_clean[0:2], 16)
    g = int(hex_clean[2:4], 16)
    b = int(hex_clean[4:6], 16)

    # Write a minimal PNG (1x1 pixel, scaled to requested dimensions via metadata)
    # This is a proper minimal 1x1 PNG
    import zlib

    def write_chunk(chunk_type: bytes, data: bytes) -> bytes:
        length = struct.pack(">I", len(data))
        body = chunk_type + data
        crc = struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)
        return length + body + crc

    # PNG signature
    png_sig = b"\x89PNG\r\n\x1a\n"

    # IHDR: width=32, height=32, bit_depth=8, color_type=2 (RGB)
    w, h = min(width, 256), min(height, 256)
    ihdr_data = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)
    ihdr = write_chunk(b"IHDR", ihdr_data)

    # IDAT: solid color rows
    raw_rows = b""
    for _ in range(h):
        raw_rows += b"\x00" + bytes([r, g, b] * w)  # filter=None, then RGB pixels

    compressed = zlib.compress(raw_rows, 9)
    idat = write_chunk(b"IDAT", compressed)

    iend = write_chunk(b"IEND", b"")

    png_bytes = png_sig + ihdr + idat + iend

    with open(full_path, "wb") as f:
        f.write(png_bytes)

    return ToolCallResponse(
        success=True,
        data={"path": path, "width": w, "height": h, "size": len(png_bytes)},
    )


def asset_generate_sprite(
    *,
    project_path: str,
    prompt: str,
    save_path: str,
    width: int = 64,
    height: int = 64,
) -> ToolCallResponse:
    """Generate a sprite using AI image API (returns prompt for external generation)."""
    # In a full implementation this would call an image generation API.
    # For now, generate a placeholder and return the prompt for the extension to use.
    placeholder_result = asset_generate_placeholder_sprite(
        project_path=project_path,
        name=os.path.basename(save_path).replace(".png", ""),
        width=width,
        height=height,
        save_path=save_path,
    )
    return ToolCallResponse(
        success=True,
        data={
            **placeholder_result.data,  # type: ignore[arg-type]
            "image_prompt": prompt,
            "note": "Placeholder generated. Use the image_prompt with an AI image API for the real sprite.",
        },
    )


def asset_list(
    *,
    project_path: str,
    type_filter: str | None = None,
) -> ToolCallResponse:
    """List all assets in the project's assets directory."""
    assets_dir = os.path.join(project_path, "assets")
    if not os.path.exists(assets_dir):
        return ToolCallResponse(success=True, data={"assets": [], "count": 0})

    type_map = {
        ".png": "texture", ".jpg": "texture", ".jpeg": "texture", ".webp": "texture",
        ".glb": "model", ".gltf": "model",
        ".ogg": "sound", ".wav": "sound", ".mp3": "sound",
        ".gdshader": "shader",
        ".tres": "resource",
        ".tscn": "scene",
    }

    results = []
    for root, _, files in os.walk(assets_dir):
        for fname in files:
            full = os.path.join(root, fname)
            ext = os.path.splitext(fname)[1].lower()
            asset_type = type_map.get(ext, "other")
            if type_filter and asset_type != type_filter:
                continue
            rel = "res://" + os.path.relpath(full, project_path).replace("\\", "/")
            results.append({
                "path": rel,
                "type": asset_type,
                "size": os.path.getsize(full),
                "name": fname,
            })

    return ToolCallResponse(success=True, data={"assets": results, "count": len(results)})
